import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SomeComponent, Footer } from "../components/SomeComponent";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <SomeComponent />

        <Footer />
      </body>
    </div>
  );
}
